<?php
/**
 * Created by PhpStorm.
 * User: intern
 * Date: 2017/10/17
 * Time: 下午4:18
 */
namespace app\admin\controller;

use think\Controller;

class Bis extends Controller{

    private $obj;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->obj = model('Bis');

    }

    public function index(){

        $res = $this->obj->getBisByStatus(1);

        return $this->fetch('', [
            'bis' => $res
        ]);

    }

    public function apply(){

        $res = $this->obj->getBisByStatus(0);

        return $this->fetch('', [
            'bis' => $res
        ]);
    }

    public function dellist(){

        $res = $this->obj->getBisByStatus(-1);

        return $this->fetch('', [
            'bis' => $res
        ]);
    }

    public function detail(){

        //获取id
        $id = input('param.id');

        //bis表
        $bis = $this->obj->get($id);

        //拼接图片
//        $bis['logo'] = str_replace("",'/','');
        $bis['logo'] = request()->domain().$bis['logo'];
        $bis['licence_logo'] = $this->request->domain().$bis['licence_logo'];

        //获取城市
        $cities = model('City')->getNormalCitiesByParentId();

        //获取二级城市
//        $se_cities = model('City')->getNormalCitiesByParentId(
//          intval($bis['city_id'])
//        );

        //获取category
        $categories = model('Category')->getAllFirstNormalCategories();

        //获取城市拼接字符
        $cityStr = $bis['city_path'];
//        if(pre)
        //分割成数组
        $arraC = explode(',',$cityStr);

        //取出第一位
        $city = $arraC[0];
        //取出第二位
        $se_city = $arraC[1];

        //获取二级城市
        $second_city = model('City')->get(['id'=>$se_city]);

        //bisLocation
        $bisLocation = model('BisLocation')->get([
            'bis_id' => $bis['id'],
            'is_main' => 1
        ]);

        //bisAccount
        $bisAccount = model('BisAccount')->get([
            'bis_id' => $id
        ]);

        return $this->fetch('',[
            'bis' => $bis,
            'city' => $city,
            'second_city' => $second_city,
            'cities' => $cities,
            'bisLocation' => $bisLocation,
            'bisAccount' => $bisAccount,
            'categories' => $categories,
        ]);

    }

    //修改状态的方法
    public function status(){
        /*
         * 以下方法不严谨,
         * 第一,如果ID,status为空,就给了默认值,造成后果,1.代码继续进行,最后返回无意义的结果(何不为空直接返回),2.默认值,返回我们不想要的结果.
         */
        //获取ID和status
        $id = input('id',0,'intval');
        $status = input('status', 0, 'intval');


        //修改bis, bisAccount, bisLocation
        $bis = $this->obj->save(['status'=>$status],['id'=>$id]);

        $bisLocation = model('bisLocation')->save(['status'=>$status], [
            'bis_id'=>$id,
            'is_main' => 1
        ]);
        $bisAccount = model('bisAccount')->save(['status'=>$status],[
            'bis_id'=>$id,
            'is_main' => 1
        ]);

        if($bis && $bisLocation && $bisAccount){
            $this->success('成功');
        }

        $this->error('失败');

    }

}