<?php
/**
 * Created by PhpStorm.
 * User: intern
 * Date: 2017/10/11
 * Time: 下午4:44
 */

namespace app\admin\controller;

use think\Controller;

class Category extends Controller{

    public $obj;

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->obj = model('Category');
    }

    public function index(){

        //获取parent_id 接受来自子栏目的id
        $parent_id = input('parent_id',0,'intval');

        //通过model获取分类数据
        $data = $this->obj->getFirstNormalCategories($parent_id);


        return $this->fetch('',[
            'categories' => $data
        ]);


    }

    /*
     * 修改状态的函数
     */
    public function status(){

        //获取参数
        $data = input();

        //校验
        $validate  = validate('Category');
        $res = $validate->scene('status')->check($data);

        if(!$res)
        {
            $this->error($validate->getError());
        }

        //进入数据库修改状态
        $result = $this->obj->save(['status'=>$data['status']],['id'=>$data['id']]);

        if(!$result){
            $this->error('状态更新失败');
        }

        $this->success('状态更新成功');

    }

    /*
     * 进入添加页面
     */
    public function add(){
        //获取一级分类

        $data = $this->obj->getAllFirstNormalCategories();

        return $this->fetch('',[
            'categories' => $data
        ]);
    }

    /*
     * 添加保存
     */
    public function save(){

        if(!request()->isPost()){
            return '保存失败';
        }

        $data = input('post.');
        //校验数据
        $validate = validate('Category');
        $res = $validate->scene('add')->check($data);

        if(!$res){
            $this->error($validate->getError());
        }

        //添加失败
        $result = $this->obj->save($data);

        if(!$result){
            $this->error('添加失败');
        }

        $this->success('添加成功',url('Category/index'));

        $this->redirect('','','','');
    }

    public function edit(){

        $id = input('id',0,'intval');
        //根据ID获取一行的信息
        $category  = $this->obj->get($id);
        $data = $this->obj->getAllFirstNormalCategories();

        return $this->fetch('',[
           'category' => $category,
            'categories' => $data
        ]);
    }

    public function update(){

        $data = input();

        $validate = validate('Category');

        $res = $validate->scene('update')->check($data);

        if(!$res){
            $this->error($validate->getError());
        }

        //修改数据
        $result = $this->obj->save([
            'name' => $data['name'],
            'parent_id' => $data['parent_id']

        ],[
            'id' => $data['id']
        ]);

        if(!$result){
            $this->error('修改失败');
        }

        $this->success('修改成功');

    }

    //排序
    public function listorder(){

//        print_r(input('post.'));

        $data = input('post.');

        $validate = validate('Category');

        $res = $validate->scene('listorder')->check($data);

        if(!$res){
            $this->error($validate->getError());
        }

       $result = $this->obj->save(['listorder'=> $data['id']],[
            'id' => $data['id']
        ]);

        if(!$result){
            $this->result($_SERVER['HTTP_REFERER'],0,'error');
        }

        $this->result($_SERVER['HTTP_REFERER'],1, 'success');

    }

    public function test(){

        $res = \Map::getStaticImage("福建省宁德市寿宁一中");

        return $res;
    }


}